config/routes.rb
Rails.application.routes.draw do

 
  root "projects#index"

  resources :sessions, only: [:new, :create, :destroy]

  resources :users 
  
  resources :projects do
    resources :pledges
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pledge.rb
class Pledge < ApplicationRecord
    belongs_to :user
    belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :pledges
    has_many :users, through: :pledges
    

end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password

    validates :email, presence: true, uniqueness: true

    has_many :pledges
    has_many :projects, through: :pledges
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :check_logged_in

    def check_logged_in
        
        if !session.include?(:user_id)
            redirect_to new_session_path
        end
    end

end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  def index
  end

  def new
  end

  def create
    @project = Project.find(params[:project_id])
    payload = pledge_params
    payload[:user_id] = session[:user_id]
    @project.pledges.create(payload)
    redirect_to project_path(@project)
  end

  def destroy
  end

  def show
  end

  private

  def pledge_params
    params.require(:pledge).permit(:amount)
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
    @project = Project.new
    @user = User.find(session[:user_id])
  end

  def create
    Project.create(project_params)
    puts Project.all.count
    redirect_to projects_path
  end

  def destroy
    Project.delete(params[:id])
    redirect_to projects_path
  end

  def show
    @project = Project.find(params[:id])
    
  end

  private

  def project_params
    params.require(:project).permit(:title, :goal)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :check_logged_in, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by({email: params["session"]["email"]})
    if user && user.authenticate(params["session"]["password"])
      session[:user_id] = user.id
      redirect_to projects_url
    else
      redirect_to new_user_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end


  private 

  def email_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :check_logged_in, only: [:new, :create]

  def index
  end

  def new
    @user = User.new
  end

  def show
  end

  def create
    user = User.create(user_params)
    session[:user_id] = user.id
    redirect_to projects_path
  end

  def destroy
  end

  def show
  end

  private

  def user_params 
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KickstarterRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pledges/create.html.erb
<h1>Pledges#create</h1>
<p>Find me in app/views/pledges/create.html.erb</p>

app/views/pledges/destroy.html.erb
<h1>Pledges#destroy</h1>
<p>Find me in app/views/pledges/destroy.html.erb</p>

app/views/pledges/index.html.erb
<h1>Pledges#index</h1>
<p>Find me in app/views/pledges/index.html.erb</p>

app/views/pledges/new.html.erb
<h1>Pledges#new</h1>
<p>Find me in app/views/pledges/new.html.erb</p>

app/views/pledges/show.html.erb
<h1>Pledges#show</h1>
<p>Find me in app/views/pledges/show.html.erb</p>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/index.html.erb
<!DOCTYPE html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<header style="display:flex;">
<h1 style="flex:auto">Projects</h1>
<div style="display:block;">
    <h3 style="float:right; clear:both">Logged in as: <%=@user.email%></h3>
    <h3 style="float:right; clear:both"><%=link_to "Logout", session_path(:session), method: :delete%></h3>
</div>
</header>
<hr>
<%@projects.each do |project|%>

    <div style="border:2px solid black; margin:2px; padding:5px;">
        <h4><%=link_to project.title, project_url(project)%></h4>

        <div>
            <p>Goal: £<%=project.goal%></p>
            <p>Current total: £<%=project.pledges.reduce(0) {|total, p| total + p.amount}%></p>
        </div>

        <%# percentage variable %>
        <%  @current =  project.pledges.reduce(0) {|total, p| total + p.amount}
            @goal = project.goal
            @percentage = (@current.to_f.round(2) / @goal.to_f.round(2)) * 100
        %>

        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="<%=@percentage%>"
                aria-valuemin="0" aria-valuemax="<%=@goal%>" style="width:<%=@percentage > 100.to_f ? 100 : @percentage%>%">

                    

                    <%=@percentage > 100.to_f ? 100 : @percentage%>%
            </div>
        </div>

        <%=form_with model: project, method: :delete, local: true do |f|%>
            <%=f.submit value="delete"%>
        <%end %>

      

    </div>

<%end%>

<hr>

<div style="margin:auto; text-align:center; padding:5px; border: 2px solid black; width: 50%">
    <h2>Create A Project</h2>

    <%=form_with model: @project, local: true do |f|%>
        <p>Title:</p>
        <%=f.text_field :title, required: true, placholder: "Title"%>
        <p>Goal:</p>
        <%=f.number_field :goal, required: true%>
        <p style="margin: 20px 0 25px;"><%=f.submit value: "Create project"%></p>
    <%end%>

</div>

app/views/projects/show.html.erb
<header style="display:flex;">
    <h1 style="flex:auto;"><%=@project.title%></h1>
    <%=link_to "Homepage", projects_url%>
</header>

<hr>
<h2>Goal: £<%=@project.goal%></h2>
<h2>Pledges:</h2>
<hr>

<%@project.pledges.each do |pledge|%>
    <p><%=pledge.user.email%> donated: £<%=pledge.amount%></p>
<%end%>

<%=form_with model: [@project, @project.pledges.build] do |pledge|%>
    <%=pledge.number_field :amount, required: true, placeholder: "£" %>
    <%=pledge.submit value: "Donate" %>
<%end%>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<%=form_with model: @user, local: true do |f|%>

    <%=f.text_field :email, type: :email, required: true%>
    <%=f.password_field :password, required: true%>
    <%# <%=f.password_field :password, required: true%>
    <%=f.submit value: "Create user"%>

<%end%>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>